# Generated by Django 3.1.6 on 2021-02-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='title',
            new_name='name',
        ),
    ]
